# Generated by Django 3.0.7 on 2020-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CADRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('des', models.CharField(blank=True, max_length=50, null=True)),
                ('orbit_id', models.IntegerField(blank=True, null=True)),
                ('jd', models.FloatField(blank=True, null=True)),
                ('cd', models.DateTimeField(blank=True, null=True)),
                ('dist', models.FloatField(blank=True, null=True)),
                ('dist_min', models.FloatField(blank=True, null=True)),
                ('dist_max', models.FloatField(blank=True, null=True)),
                ('v_rel', models.FloatField(blank=True, null=True)),
                ('v_inf', models.FloatField(blank=True, null=True)),
                ('t_sigma_f', models.CharField(blank=True, max_length=50, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireballRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('impact_e', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lat_dir', models.CharField(blank=True, max_length=1, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lon_dir', models.CharField(blank=True, max_length=1, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('vel', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
